// packages/vue/stories/Palette.vue
<script setup lang="ts">
import { Button, ExtendedButton} from './palette'

withDefaults(defineProps<{
  _primary: boolean,
  _primaryColor: string,
  _size: string,
  label: string,
  disabled: boolean
}>(), {
  _primary: false,
  _primaryColor: "#f18805",
  _size: 'normal',
  label: '',
  disabled: false
})
</script>

<template>
  <Button v-bind:_primary v-bind:_primaryColor v-bind:_size v-bind:disabled>{{label}}</Button>
  <ExtendedButton v-bind:_primary v-bind:_primaryColor v-bind:_size v-bind:disabled>Test</ExtendedButton>
</template>

// packages/svelte/stories/Palette.svelte
<script lang="ts">
  import { Button, ExtendedButton} from './palette'

  import { createEventDispatcher } from 'svelte'

  export let _primary = false
  export let _primaryColor = "#f18805"

  export let _size: 'normal' | 'small' = 'normal'

  export let label = ''

  export let disabled

  const dispatch = createEventDispatcher()

  /**
   * Optional click handler
   */
  function onClick(event) {
    dispatch('click', event)
  }
</script>

<Button {_primary} {_size} {_primaryColor} {disabled} on:click={onClick}>
  {label}
</Button>
<ExtendedButton {_primary} {_size} {_primaryColor} {disabled}>Test</ExtendedButton>
