// packages/vue/stories/Theme.vue
<script setup lang="ts">
import type { CustomTheme } from './customTheme'

import { Component } from './theme'
import { ThemeProvider } from '@teiler/vue'

defineProps({
  theme: {
    type: Object as () => CustomTheme,
    default: () => ({
      fontColor: 'red',
    })
  }
});
</script>
<template>
  <ThemeProvider :theme="theme">
    <Component>Some test text</Component>
    Color: {{ theme.fontColor }}
  </ThemeProvider>
</template>

// packages/svelte/stories/Theme.svelte
<script lang="ts">
  import type { CustomTheme } from './customTheme'

  import { ThemeProvider } from '@teiler/svelte'
  import { Component } from './theme'

  const { theme = { fontColor: 'red' } }: { theme?: CustomTheme } = $props()
</script>

<ThemeProvider {theme}>
  <Component>Some test text</Component>
</ThemeProvider>
