// packages/svelte-v5/stories/Theme.svelte
<script lang="ts">
  import type { CustomTheme } from './customTheme'

  import ThemeProvider from '../src/ThemeProvider.svelte'
  import { Component } from './theme'

  export let theme: CustomTheme = {
    fontColor: 'red',
  }
</script>

<ThemeProvider {theme}>
  <Component>Some test text</Component>
</ThemeProvider>

// packages/vue/stories/Theme.vue
<script setup lang="ts">
import type { CustomTheme } from './customTheme'

import { Component } from './theme'
import ThemeProvider from '../src/ThemeProvider';

defineProps({
  theme: {
    type: Object as () => CustomTheme,
    default: () => ({
      fontColor: 'red',
    })
  }
});
</script>
<template>
  <ThemeProvider :theme="theme">
    <Component>Some test text</Component>
    Color: {{ theme.fontColor }}
  </ThemeProvider>
</template>
